### ISSUE TITLE
No license provided

### ISSUE THREAD

**Issue by ModEngineer** [AzureDVBB/Blender-UI-Examples#1]
Hey AzureDVBB, what's the license for the Blender-UI-Examples repo? I've looked around, and the code here is the cleanest that I've found. I'd like to know the license because I'd like to use(and modify) the code here for one of my own addons without any licensing or copyright issues. The addon I'm working on will be open source and available for free under the MIT License.

**Comment by ModEngineer** [comment]
When providing a license, could you commit it directly as the "LICENSE" (without quotes) file at the root of the repo? Thank you!

**Comment by AzureDVBB** [comment]
Ah good catch, didn't really know alot about licensing back when I posted this. One moment!

**Comment by ModEngineer** [comment]
Oh my that was fast... Thank you so much!

**Comment by ModEngineer** [comment]
Update: Apologies for stating the wrong license. About Blender add-ons, they need to be licensed under GPLv3, so this would require the GPLv3 license.

**Comment by AzureDVBB** [comment]
Hmm.. from a cursory glance I do not know if it would be problematic for me to keep this under MIT. And you are free to change derivative work's licences under it as it is a very permissive licence, unlike GPLv3 which requires derivative works to be under the same licence.

From the Blender website https://www.blender.org/about/license/

"Sharing or selling Blender add-ons (Python scripts)

Blender’s Python API is an integral part of the software, used to define the user interface or develop tools for example. The GNU GPL license therefore requires that such scripts (if published) are being shared under a GPL compatible license. You are free to sell such scripts, but the sales then is restricted to the download service itself. Your customers will receive the script under the same license (GPL), with the same free conditions as everyone has for Blender.

Sharing Blender or Blender add-ons or scripts is always OK and not considered piracy."

I think this is considered under the final clause, in addition this isn't an add-on but a script with useful comments.
The derivative work can be under GPLv3 as is required, owed to the fact that MIT allows that.

But if you think there is a licensing issue I can change it easily, takes me quite literally two minutes. I'm mostly just curious if there is actually some licensing incompatibilities or not for future reference.

What do you think?

**Comment by ModEngineer** [comment]
I'd like to open by saying that I am not a lawyer. This is not legal advice. I am simply stating the current situation as I understood it.

GPLv3 and licensing as a whole are complicated. Your add-on is considered a derivative work solely because it depends on Blender, which as a whole, is GPLv3, thus requiring your work to be GPL'ed as well. That's not to say that all of your code has to be GPLv3 though. While your add-on as a whole must be GPLv3 and any derivative works must also be under the same license, your add-on could use a non-GPL'ed library as a dependency, such as how my add-on uses an Apache 2.0 library.

I'd like to close by saying that I am not a lawyer, this isn't legal advice, and that you can do whatever you think best fits this situation.

**Comment by AzureDVBB** [comment]
Alright, cheers! Updated the licence to be GPLv3
